### ISSUE TITLE
Upper bound on yaml

### ISSUE THREAD

**Issue by snoyberg** [axellang/axel#21]
yaml-0.10.2.0 (Michael Snoyman michael@snoyman.com @snoyberg) is out of bounds for:
- [x] axel-0.0.5 (>=0.8.31 && < 0.10). Joshua Grosso <jgrosso256@gmail.com> @jgrosso. @axellang. Used by: library

**Comment by jgrosso** [comment]
`axel-0.0.5` update via a Hackage revision.

**Comment by snoyberg** [comment]
Thanks for the super fast response!
